### ISSUE TITLE
xpath selector

### ISSUE THREAD

**Issue by guhagaurav** [SelectorsHub/SelectorsHubIssues#1]
Steps to Reproduce:

1. Goto Google.com homepage
2. use selector $x("//div[@class='grid-tile-container']") in console. You would see 10 elements.
3. use the same selector in selectorshub, No elements displayed

**Comment by selectorshubsanjay** [comment]
Thank you Gaurav for highlighting this. This is not an issue.
You are trying wrong syntax, you should try only xpath or cssSelector in SelectorsHub.
Use the below selector in SelectorsHub and you will get the same result.
//div[@Class='grid-tile-container']

**Comment by guhagaurav** [comment]
I have tried the same way before. Please see the screen below
![image](https://user-images.githubusercontent.com/42951074/88955351-6bf19a80-d2b9-11ea-94fb-2d038eec2089.png)

**Comment by selectorshubsanjay** [comment]
In console also it 0.
Actually google.com has all the attributes very dynamic. So please it might got change. Please try for some other element.

![image](https://user-images.githubusercontent.com/67390539/88955660-d7d40300-d2b9-11ea-80bf-11653348fe8f.png)

**Comment by guhagaurav** [comment]
Sorry the issue is in page which have last visited sites added as thumbnails.  Inspect to any of the shortcut thumbnail then try the xpath in console. Please see the screens below.

![image](https://user-images.githubusercontent.com/42951074/88956796-8593e180-d2bb-11ea-972e-3fa05fadd1b1.png)

![image](https://user-images.githubusercontent.com/42951074/88956846-9c3a3880-d2bb-11ea-8c33-8e0e5ba464a4.png)

**Comment by selectorshubsanjay** [comment]
If auto suggest doesn’t work while building Selectors at google.com

1.     Make sure in the browser you have opened google.com and it’s not default chrome blank tab.
2.     Don’t try on blank tab. There should be a url in address bar as it will not support on blank new tab.
3.     Also Extensions won’t support on Extensions store website so try on a genuine website.

https://www.selectorshub.com/faq/
