### ISSUE TITLE
Typing //svg suggests xpath when it should not be

### ISSUE THREAD

**Issue by gauravkhuraana** [SelectorsHub/SelectorsHubIssues#10]
when you type //svg , selectorshub gives autosuggestion 

When you select those suggestions they get appended to //svg[@id='tets'] example

//svg is not the right path.. So ideally it should not give suggestion

**Comment by selectorshubsanjay** [comment]
Thank you Gaurav for the great suggestion. I will implement this in next release. 
Appreciate it and keep supporting.

**Comment by selectorshubsanjay** [comment]
This is done and feature is live now. Please test it and please feel free to let me know if there is any issue or further improvement can be done.
