### ISSUE TITLE
SelectorsHub Facebook issue

### ISSUE THREAD

**Issue by tuetranduy** [SelectorsHub/SelectorsHubIssues#11]
Hi support team,

I am facing an issue when using Facebook with SelectorsHub installed on Chrome.
Facebook seems not responding when using right-click with SelectorsHub add-on turned on. This issue will not happen when I remove/disable SelectorsHub.

I think this is a performance issue, I also attach screenshots with CPU consume when using FB with and without SelectorsHub.

- With SelectorsHub - sometimes takes 130% when right-click many many times
![image](https://user-images.githubusercontent.com/23623560/96724074-9f842280-13d9-11eb-80b0-8627f05914f9.png)

- Without SelectorsHub
![image](https://user-images.githubusercontent.com/23623560/96724283-dc501980-13d9-11eb-8df8-5c2e9c19104a.png)

Step to reproduce:
- right-click many times on the FB page with SelectorsHub turned on

=> result: FB page is not responding.

I'm using Macbook Pro 13 inch 2017 with Core i7 (3,5 GHz), 16gb RAM

**Comment by selectorshubsanjay** [comment]
Thank you for writing and sharing the details.

Yes on Facebook this issue happened.
Reason- When you write click it used to generate all types of Selectors and facebook is very heavy page so it takes time to traverse thru the DOM to generate selectors for that element.

So here is the solution- You can turn off the context menu option so it work like charm.

Please checkout this video.

https://youtu.be/2gH5c97j2GU?t=1431

Kindly let me know if you still face the issue. Thank you.

**Comment by tuetranduy** [comment]
Thank you for quicky response. Yes, it works well when I turn off the context menu option.

In this case, I think it will be better to add the white/blacklist feature to prevent SelectorsHub on unwanted websites.

Regards,
