### ISSUE TITLE
Unable to fetch xpaths typed previously in the selectorshub by pressing Ctr+Z

### ISSUE THREAD

**Issue by rizwanaabdulkalam** [SelectorsHub/SelectorsHubIssues#13]
Hi Sanjay,

Following are the steps:
Write an xpath in selectors hub textbox for locating an element > Do modifications to this xpath multiple time > I want to go back to the xpath I have typed initially > Pressing Ctr+Z does not take me back to the previously written xpaths > Same is applicable to moving forward with Ctr+Y

This is possible in chrome dev tools. Hence, I think it will be helpful for people trying out different xpaths and wants to undo/ redo things

Thanks
Rizwana

**Comment by selectorshubsanjay** [comment]
Thank you Rizwan, I am fixing this right away. Much appreciated your support.

**Comment by selectorshubsanjay** [comment]
I hope this is working fine now. I am closing the issue.
Kindly let me know if you face this issue again. Thank you.
