### ISSUE TITLE
Scroll down or up not functional

### ISSUE THREAD

**Issue by AmajWardak** [SelectorsHub/SelectorsHubIssues#14]
I tried to use find the dom element for an embedded section in page. But selectorhub is not able to find the dom element for the scrolling section of the page.

**Comment by selectorshubsanjay** [comment]
Thank you Amaj for letting me know about it. Request you if possible please share the website and scenario where it is failing so I can fix it and test.

**Comment by selectorshubsanjay** [comment]
I hope this is working fine now. I am closing the issue.
Kindly let me know if you face this issue again. Thank you.
