### ISSUE TITLE
Drop selection text not working

### ISSUE THREAD

**Issue by Dinesh9632** [SelectorsHub/SelectorsHubIssues#15]
Hi Team,

How can we select the text under dropdown list, in Dev tools its possible by using value in contains method?

Could you please help this issue?

Thanks,

**Comment by selectorshubsanjay** [comment]
Sure Dinesh, I am here to help you. 
Just inspect the dropdown values, SelectorsHub will auto generate xpath. You can also copy the xpath value just by right on that element. 
Please follow this video tutorial to make best use of SelectorsHub.
https://www.youtube.com/watch?v=2gH5c97j2GU&feature=youtu.be
