### ISSUE TITLE
Close button does not work for announcement (Safari)

### ISSUE THREAD

**Issue by gauravkhuraana** [SelectorsHub/SelectorsHubIssues#19]
Click on the **close** icon on announcement. It should get closed, but it does not.

![image](https://user-images.githubusercontent.com/15048211/108826544-6c9da580-75ea-11eb-88c0-1260556e9a87.png)

Issue of less priority/severity but it's a problem.

Problem is in edge browser

**Comment by selectorshubsanjay** [comment]
Hi Gaurav,
I just tried on Edge in Mac OS and it worked fine.
Edge version : 88.0.7
SelectorsHub version : 2.1.4
Could you please refresh the page and then try again once.

![image](https://user-images.githubusercontent.com/67390539/108866494-455ecc80-761a-11eb-81c6-80eda570dcd7.png)

![image](https://user-images.githubusercontent.com/67390539/108866432-35df8380-761a-11eb-9bfe-1bb45f2108ef.png)

**Comment by gauravkhuraana** [comment]
https://i.imgur.com/nJahsGI.gif

looks like version 90 has this problem

**Comment by selectorshubsanjay** [comment]
Thank you Gaurav for the information. I will test this on 90 version and will fix it.

**Comment by selectorshubsanjay** [comment]
The close button have been removed, now just click on the announcement link to hide the banner. Thank you.

**Comment by gauravkhuraana** [comment]
Sure thanks will test once it comes.. to production,, as of now i see version 2.1.6 on edge.. and the announcement is not coming to retest

**Comment by selectorshubsanjay** [comment]
Yes Gaurav, it's under review from edge side. It will be available with 2.1.7.
Yes once you click on the announcement banner it won't show again. I have made it as feature so it won't keep annoying users as they have already clicked on that.
Let me know your thoughts on this.
