### ISSUE TITLE
unable to find xpaths using selectorHub

### ISSUE THREAD

**Issue by rghule-egain** [SelectorsHub/SelectorsHubIssues#2]
I performed the steps mentioned in the video tutorial. It is not working for me. when i entered // nothing is auto suggested. even with the css

**Comment by selectorshubsanjay** [comment]
If auto suggest doesn’t work while building Selectors at google.com

1. Make sure in the browser you have opened google.com and it’s not default chrome blank tab.
2. Don’t try on blank tab. There should be a url in address bar as it will not support on blank new tab.
3. Also Extensions won’t support on Extensions store website so try on a genuine website.

For more details pls check here-
https://www.selectorshub.com/faq/

If issue still persist, kindly let me know. Thank you.

**Comment by selectorshubsanjay** [comment]
Please follow this video, it will help you, Thank you.
https://youtu.be/v2DRbQH-C7Q

**Comment by rghule-egain** [comment]
Hi. 
i tried on my web application, was not working when i raised the issue.
But its working now. Thanks
Fantastic utility

**Comment by selectorshubsanjay** [comment]
Thank you Rahul.
