### ISSUE TITLE
Feature Request :- Can you give an option to not show the dropdown while typing selector

### ISSUE THREAD

**Issue by gauravkhuraana** [SelectorsHub/SelectorsHubIssues#21]
Please give a **toggle** button so we don't see this. Good for people who are learning selectors

So good features of selectors hub will still be there. but not dropdown

![image](https://user-images.githubusercontent.com/15048211/112275636-d1a9f100-8ca5-11eb-9529-53fe69241186.png)

**Comment by gauravkhuraana** [comment]
You can name it as **expert Mode**

**Comment by selectorshubsanjay** [comment]
This feature is live now on Edge browser with 3.0.5 version.
Kindly verify it and let me know if any issue. Thank you.
