### ISSUE TITLE
Not able to read the text because of color combination on wrong syntax

### ISSUE THREAD

**Issue by gauravkhuraana** [SelectorsHub/SelectorsHubIssues#22]
Color combination makes it hard to read 

enter a wrong xpath some copy paste from somehere and we see like below.. This color combination make it hard for user to read

![image](https://user-images.githubusercontent.com/15048211/112279562-0f107d80-8caa-11eb-98da-4e0ac3a5c649.png)

tested in edge

**Comment by selectorshubsanjay** [comment]
Thank you Gaurav for reporting this issue. I have fixed this issue, it will be available very soon with 3.0.5 version.

**Comment by selectorshubsanjay** [comment]
Fix is live now on Edge browser with the version 3.0.5.
It is under review on chrome and will be live soon. 
Kindly verify it and let me know if any issue. Thank you.
