### ISSUE TITLE
Label is not there for textbox which makes it difficult for user to understand purpose of the textbox

### ISSUE THREAD

**Issue by gauravkhuraana** [SelectorsHub/SelectorsHubIssues#23]
This option(**blank textbox**) comes without a name.

Better to give some heading for this page like iframe/shadowDOM element information. Something like that 

So the people seeing for first time might not be confused

![image](https://user-images.githubusercontent.com/15048211/112289190-16d51f80-8cb4-11eb-8056-f8d2680777e5.png)

**Comment by selectorshubsanjay** [comment]
Thank you Gaurav for highlighting this issue. Now this box will not show until there is no nested iframe or shadow DOM.

**Comment by selectorshubsanjay** [comment]
Fix is live now on Edge browser with the version 3.0.5.
It is under review on chrome and will be live soon. 
Please verify it and if any issue kindly let me know. Thank you.
