### ISSUE TITLE
In Firefox, I am not getting script for nested shadow dom objects . I could see in chrome though. Could you please verify?

### ISSUE THREAD

**Issue by divya25sep** [SelectorsHub/SelectorsHubIssues#24]

**Comment by selectorshubsanjay** [comment]
Yes Divya, SelectorsHub 3.0 version is not yet released on Firefox yet. This is the reason you are not able to find script for shadow dom element. It will be released soon on firefox. Thank you.

**Comment by selectorshubsanjay** [comment]
Hi Divya, 3.0 is live now on Firefox.
Please update it and now you will ge the nested shadow dom support and all the features.
https://addons.mozilla.org/en-US/firefox/addon/selectorshub/

**Comment by divya25sep** [comment]
Ok thanks for informing

Sent from Mail for Windows 10
