### ISSUE TITLE
AutoGenerated Xpath - incorrect syntax 

### ISSUE THREAD

**Issue by AnyaAR** [SelectorsHub/SelectorsHubIssues#25]
When I use auto generated Xpath with driver.findeElement command I noticed that the syntax is incorrect:
driver.findElement(By.xpath("//img[@alt='OrangeHRM on Facebook']')) - it shoud be ---> Facebook']"))    at the end. I got the same issue twice when copied auto generated Rel Xpath. 

![image](https://user-images.githubusercontent.com/81732009/113244029-1109ac00-9269-11eb-92f8-87a988a0ce84.png)

**Comment by selectorshubsanjay** [comment]
Here you have entered the invalid command. 
In the command you have used ----> "xpathvalue'
That is the reason it is generated invalid command. 

Please use --> "xpathvalue"

Please follow this video tutorial for more details.

**Comment by AnyaAR** [comment]
Thank you, it fixed the issue.
