### ISSUE TITLE
Cosmetic Issue: Tooltip for the button "Set Attibute" gets hidden in multiple xpaths mode.

### ISSUE THREAD

**Issue by sankalprao** [SelectorsHub/SelectorsHubIssues#26]
**Steps to Reproduce:**

1. Open browser with SelectorsHub installed.
2. Click on multiple xpaths mode and hover over set attribute button
3. Notice that the tooltip get hidden behind the multiple xpaths window headings.

Note: Please see the attached gif for better understanding.

![SHToolTipIssue](https://user-images.githubusercontent.com/36331783/114513217-4ce73d00-9c7d-11eb-9180-455401079279.gif)

**Comment by selectorshubsanjay** [comment]
Thank you Sankalp for highlighting this issue. I have fixed this issue and it will be available in soon with the next release 3.0.8.

![image](https://user-images.githubusercontent.com/67390539/114547401-09400380-9c7c-11eb-8ca8-e4a2d771c9bd.png)

**Comment by selectorshubsanjay** [comment]
This fix is live now with 3.0.8 release. Please verify it. Thank you.
