### ISSUE TITLE
SH locator option provided by SelectorsHub as recommended option uses dynamic attribute to generate locator.

### ISSUE THREAD

**Issue by sankalprao** [SelectorsHub/SelectorsHubIssues#28]
For the purpose of illustrating this issue, I could find a suitable example website. I have observed that the SH Selector option provided by SelectorsHub ( as a recommended option) generates locator using a dynamic attibute (ex: class ). Right under that for relative xpath option, it throws a warning that the attribute with which it is generated is dynamic and uncheck the class checkbox to generate using a different unique attribute. If the attribute is dynamic, then the SH locator suggestion should automatically generate locator option with a different unique attribute as users blindly take that SH locator option and use it in their scripts.

![image](https://user-images.githubusercontent.com/36331783/114527285-27f9c680-9c8b-11eb-9187-120ed4508843.png)

**Comment by selectorshubsanjay** [comment]
You are right Sankalp, it should go with the static value attribute but here in SelectorsHub it has preference based on attribute type. To understand more about attribute preference in SelectorsHub, please checkout this video once.
https://youtu.be/yti5o3ILxlU

Actually many a times values which looks dynamic in case of attributes are static so I have given preference to attribute over value. For ex- checkout google.com
Here you will feel class values are dynamic but all of them are static. So here i have given choice to user to decide what they want and what attribute is suitable for their application. 

Feel free to let me know if you feel we should give preference to attribute value over attribute name , we can think on that as well. thank you for your great inputs and ideas.
