### ISSUE TITLE
Is SH supporting to iframe or not?

### ISSUE THREAD

**Issue by ektadesai-sdet** [SelectorsHub/SelectorsHubIssues#29]
Getting below for most of the elements related to the frame. Is SH not supporting to iframe?

![image](https://user-images.githubusercontent.com/82146474/117286288-a01c6c00-ae86-11eb-898b-bced4b780fa4.png)

**Comment by selectorshubsanjay** [comment]
As message shown in the SH, that iframe could be a different src iframe. 
As per W3C standard, extension can't access iframe from different src that is the reason it is not able to generate selectors for them.

To learn more about it, please follow this video-
https://youtu.be/ccAGj0op2J8

If the url is public, please share. I will have a look and give more clarity on this. Thank you.

**Comment by selectorshubsanjay** [comment]
I hope this is working fine now. I am closing the issue.
Kindly let me know if you face this issue again. Thank you.
