### ISSUE TITLE
Create some option so the product itself explains about features

### ISSUE THREAD

**Issue by gauravkhuraana** [SelectorsHub/SelectorsHubIssues#30]
Product tour option should be there. 

So when a person installs they get a tour of the product.

1) There should be a button which can tell about the features as well 1 by 1 highlighting each option one by one

Alternate 
2) You can also give a link to website which has all major portions highlighted in form of pictures

It should not be too much detailed,, but covers major things so people know it has these options for what

**Comment by selectorshubsanjay** [comment]
Thank you Gaurav for the valuable suggestions. I will definitely incorporate these suggestion soon in the upcoming release.

**Comment by selectorshubsanjay** [comment]
Hi Gaurav, this enhancement is pushed with 3.1.8 release. 
It is live on firefox and soon will be available on all browsers. Thank you for this great improvement.

Now whenever user will open SelectorsHub for the first time, a small footer banner will show with the instruction page message.
It will not show 2nd time.

Here is the instruction page-
https://selectorshub.com/instructions/

**Comment by gauravkhuraana** [comment]
Do we have any on demand button also,, in case by mistake i closed it ?
or
I am using after long time and want to see some features back again, can i do that by some option to do product walkthrough

**Comment by selectorshubsanjay** [comment]
Currently, it is available on website but not in the SelectorsHub tab.
https://selectorshub.com/instructions/

![image](https://user-images.githubusercontent.com/67390539/124427023-77cac400-dd88-11eb-85cf-1979f44fa75f.png)
