### ISSUE TITLE
Unable to handle attribute values that starts with whitespace

### ISSUE THREAD

**Issue by depascalis** [SelectorsHub/SelectorsHubIssues#32]
If an elements attribute value has whitespace in the beginning of the value string, SelectorsHub fails to generate proper selectors. The correct selector for XPath is however generated. Rel cssSelector, JS Path, and Abs XPath, fails.

**Examples**:
`<div class="select-me">`
Generated selector: `.select-me`

Added whitespace
`<div class=" select-me-too">`
Generated selector: `body > div:nth-child(1)`

This bug is true for all types of attributes that I have tested on, not just the class attribute.
This bug affects Auto generated selectors and Record generated selectors

**Comment by selectorshubsanjay** [comment]
Thank you for highlighting this issue.
This issue is fixed now and will be available soon. 
I will update you once, it is live. Really appreciate your great inputs.
Feel free to let me know if you find any more improvements or issue, more than happy to fix them.

![image](https://user-images.githubusercontent.com/67390539/119452087-94201d80-bd53-11eb-9ee4-86771e4666be.png)

**Comment by depascalis** [comment]
I went to bed after filing a bunch of issues, when waking up he morning after I'm greeted with notifications telling me that all issues are fixed. What a great job man, I don't know if my day could start any better. 👏

Are you closing the issues or are you expecting the reporter to do it?

**Comment by selectorshubsanjay** [comment]
So happy to hear that. :)
I will update here once the release will be live. 
Then you can verify and can close if it will be fixed. If any further update will be required, you can keep it open and update it.

**Comment by selectorshubsanjay** [comment]
Fix is live now on Firefox. 
You can add SelectorsHub in Firefox and test it.
https://addons.mozilla.org/en-US/firefox/addon/selectorshub/

On Chrome, it's under review. It will be available within 1-2days.

Kindly close the review after testing it. Thank you.

**Comment by selectorshubsanjay** [comment]
Please find the changelog here for this release 3.1.5
https://selectorshub.com/changelog/

**Comment by depascalis** [comment]
Great work @selectorshubsanjay, everything seems to be working 👏
