### ISSUE TITLE
Auto suggestions for more :nth selectors

### ISSUE THREAD

**Issue by depascalis** [SelectorsHub/SelectorsHubIssues#34]
I'm not getting Auto suggestions for `:nth-of-type()`  and `:nth-last-of-type()` which would be preferable.

I can't elaborate more than that 😂

**Comment by selectorshubsanjay** [comment]
Thank you so much for reporting this. I have fixed this issue and it will be available soon with the next release.

![image](https://user-images.githubusercontent.com/67390539/119449778-a9e01380-bd50-11eb-9668-c10b05151505.png)

**Comment by selectorshubsanjay** [comment]
Thank you so much for reporting this. I have fixed this issue and it will be available soon with the next release.

![Uploading image.png…]()

**Comment by selectorshubsanjay** [comment]
Fix is live now on Firefox. 
You can add SelectorsHub in Firefox and test it.
https://addons.mozilla.org/en-US/firefox/addon/selectorshub/

On Chrome, it's under review. It will be available within 1-2days.

Kindly close the review after testing it. Thank you.

**Comment by depascalis** [comment]
Awesome, thanks! Works in Chrome now.
