### ISSUE TITLE
Navigation Issue - When we click the Youtube Icon on the quick action toolbar it opens a blank page instead of Youtube page

### ISSUE THREAD

**Issue by MuthukkaruppanSubramanian** [SelectorsHub/SelectorsHubIssues#35]
Steps To Reproduce:
1.Go to the Selectors Hub tab on the Dev Tools
2. Click the Youtube icon on the bottom
3. New tab will be opened

ScreenShot:
![image](https://user-images.githubusercontent.com/37132906/120598129-69118a00-c435-11eb-9cfc-f3ef3092d9d6.png)

Expected Result: Youtube page should be loaded with Tutorial for SelectorsHub3.0
Actual Result: Blank page was opened.

**Comment by selectorshubsanjay** [comment]
Thank you for reporting this issue.
I will fix it immediately and soon it will be live with 3.1.7 release.

**Comment by selectorshubsanjay** [comment]
Fix is live now on Firefox browser. Please test it here.
https://addons.mozilla.org/en-US/firefox/addon/selectorshub/

Soon it will be available on chrome with 1-2days. It's under review from chrome side.

**Comment by selectorshubsanjay** [comment]
Release is live on chrome too.
