### ISSUE TITLE
Table Alignment Issue - When we inspect an element xpath and class name row was overlapped

### ISSUE THREAD

**Issue by MuthukkaruppanSubramanian** [SelectorsHub/SelectorsHubIssues#36]
Steps To Reproduce:
1. Go to url https://testproject.io/
2. Open the Dev Tools and Inspect the text "Create your tests
wherever you want"

ScreenShot:
![SelectorsHub_table_alignment_Issue](https://user-images.githubusercontent.com/37132906/120656204-f0c9b980-c472-11eb-9b9b-5d4d1d9ae04d.png)

Element Inspected on the Web page:

![image](https://user-images.githubusercontent.com/37132906/120656332-11920f00-c473-11eb-939e-ad504aa19c71.png)

**Comment by selectorshubsanjay** [comment]
Thank you for reporting this issue.
I have fixed it and soon it will be live with 3.1.7 release. I will update you once it will be live. Thank you.

**Comment by selectorshubsanjay** [comment]
Fix is live now on Firefox browser. Please test it here.
https://addons.mozilla.org/en-US/firefox/addon/selectorshub/

Soon it will be available on chrome with 1-2days. It's under review from chrome side.

**Comment by selectorshubsanjay** [comment]
Release is live on chrome too.
