### ISSUE TITLE
UI issue

### ISSUE THREAD

**Issue by wspxh** [SelectorsHub/SelectorsHubIssues#37]
![image](https://user-images.githubusercontent.com/13498864/122853196-68895680-d344-11eb-985d-aca9f10ec72d.png)
The interface is misplaced, very ugly, and this problem has always existed from version 2.0 to 3.0

**Comment by selectorshubsanjay** [comment]
Thank you for reporting this issue. I am fixing it immediately. 
Kindly let me know if we can have a call because this issue comes only when it opens in Chinese language.

**Comment by selectorshubsanjay** [comment]
Friend, I need your help to fix this issue.
Can we have zoom call because I need to see in your browser and then only I can fix as this issue comes only for Chinese language.

**Comment by wspxh** [comment]
Ah, sorry, my network environment is not very good, so I just saw your reply. My English is not very good, and the current content is all reliant on Google Translate, so zoom may not help much, if you have For things that need to be viewed, such as logs, you can tell me the location and I will post it

**Comment by selectorshubsanjay** [comment]
No Problem.
Will you be able to join call on google hangout?
My email is selectorshub@gmail.com

**Comment by selectorshubsanjay** [comment]
Please share your email id, I will ping you there.

**Comment by wspxh** [comment]
wspxh123@gmail.com
