### ISSUE TITLE
Help text remains same while switching off and on

### ISSUE THREAD

**Issue by gauravkhuraana** [SelectorsHub/SelectorsHubIssues#40]
the help text can be changed or better change the menu name when its clicked like 

> switch on Axes menu 
> switch off Axes menu

So user can go inside or come out based on the usage

![chrome_8Mjrlo4IjC](https://user-images.githubusercontent.com/15048211/133235594-4f2a1efc-8c8b-4722-82a6-0985f262e4ad.png)

**Comment by selectorshubsanjay** [comment]
Thank you Gaurav for the suggestion. 
This is done and push with release 4.0.1.

![image](https://user-images.githubusercontent.com/67390539/133915865-a2362b11-2ba5-47e1-ac2b-1be3455e3a47.png)
