### ISSUE TITLE
Xpath is valid but selenium gives error - Element not interactable 

### ISSUE THREAD

**Issue by gauravkhuraana** [SelectorsHub/SelectorsHubIssues#43]
In this pic, the element xpath is working 

![image](https://user-images.githubusercontent.com/15048211/137261507-ab6fdcbb-879e-49b6-af72-bf24014fe88a.png)

But when we run it, selenium gives error, element not interactable. 

If SH can tell us this, it can save lot of time

**Comment by selectorshubsanjay** [comment]
Thank you Gaurav for this great suggestion. 
This feature has been implemented and pushed with 4.0.7.
Release is live on Opera. Very soon it will be available on Chrome, Edge and other browsers.

![image](https://user-images.githubusercontent.com/67390539/137514730-b94b5755-3977-4e40-b1f0-a1e84a1997a9.png)

**Comment by selectorshubsanjay** [comment]
This feature is live now.
