### ISSUE TITLE
SelectorHub extension for edge browser : Locators are not being shown for a local HTML web page

### ISSUE THREAD

**Issue by sharath1493** [SelectorsHub/SelectorsHubIssues#44]
[Locators issue on Edge Browser.docx](https://github.com/SelectorsHub/SelectorsHubIssues/files/7627144/Locators.issue.on.Edge.Browser.docx)

**Comment by selectorshubsanjay** [comment]
Hi Sharath,
To use extensions for local files, we need to provide the access of local files.
https://www.youtube.com/watch?v=kQ1jjLnQtyM

<img width="957" alt="Screenshot 2021-12-01 at 1 01 42 PM" src="https://user-images.githubusercontent.com/67390539/144191202-6b6f31b7-cc3e-4deb-a8ea-e4761ddaac8b.png">
