### ISSUE TITLE
[Enhancement] Option to copy the text attributes from result window 

### ISSUE THREAD

**Issue by gauravkhuraana** [SelectorsHub/SelectorsHubIssues#45]
Hi Sanjay

Could you please give an option to copy the attributes from the results window.

![image](https://user-images.githubusercontent.com/15048211/146158117-da9f24cd-205d-42fc-af27-ee600ee2f8fc.png)

ctrl+a does not work well

**Comment by selectorshubsanjay** [comment]
+1 
Inprogress

**Comment by selectorshubsanjay** [comment]
Done. 
Now whenever user verify xpath which returns the value (not a web element), SelectorsHub will show this copy icon (refer screenshot) to copy all the values in single shot.
This feature will be available with the release 4.1.7.
Kindly let me know if you feel any improvement required here. Thank you.

<img width="647" alt="Screenshot 2022-01-02 at 7 52 35 PM" src="https://user-images.githubusercontent.com/67390539/147878806-611d23b2-cead-4db2-8481-104c1102b963.png">
<img width="670" alt="Screenshot 2022-01-02 at 7 53 00 PM" src="https://user-images.githubusercontent.com/67390539/147878808-d9b3fae2-3f72-41c0-9ad0-ebf1b2987077.png">

**Comment by selectorshubsanjay** [comment]
This feature is live now on chrome, opera and firefox. Soon it will be available on Edge. Please test it and let me know if any improvements required. Thank you.
