### ISSUE TITLE
Enhancement Request - Change the name of Maintenance to Bulk operations 

### ISSUE THREAD

**Issue by gauravkhuraana** [SelectorsHub/SelectorsHubIssues#49]
Maintenance has some very good feature sitting inside it which are hidden from many.

They should be grouped together and highlighted so user can make the best use of it.,

Like bulk validation 
bulk export
bulk import from an automation script

**Comment by selectorshubsanjay** [comment]
Thank you for the suggestion. This feature is now introduced as "Selectors Healing"
