### ISSUE TITLE
Selectors hub is not giving results when query the details

### ISSUE THREAD

**Issue by csri9490** [SelectorsHub/SelectorsHubIssues#5]
![d2](https://user-images.githubusercontent.com/58204896/90316401-a016bd80-df3f-11ea-8013-7646084062a5.png)

**Comment by selectorshubsanjay** [comment]
Please open the devtools as attached in the bottom as show in the screenshot.

![image](https://user-images.githubusercontent.com/67390539/90319704-1cb59600-df58-11ea-83fe-9f1cab0ff6fb.png)

**Comment by selectorshubsanjay** [comment]
Please follow this video, it will solve the issue. Thank you.

https://youtu.be/v2DRbQH-C7Q
