### ISSUE TITLE
Enhancement Request - Error on missing @ for attributes

### ISSUE THREAD

**Issue by gauravkhuraana** [SelectorsHub/SelectorsHubIssues#50]
if you miss @ it shows 0 elements matching , ideally it should give error that its an invalid xpath

![image](https://user-images.githubusercontent.com/15048211/191184248-e032a25c-46e7-423e-a0fc-7665736204bb.png)

![image](https://user-images.githubusercontent.com/15048211/191184392-f930d088-8743-4cd3-b3b1-f44a5a630c24.png)

**Comment by selectorshubsanjay** [comment]
Logically this correct and if it doesn't have @, it is not invalid xpath.
