### ISSUE TITLE
Feature Request - Move cross button to the left

### ISSUE THREAD

**Issue by gauravkhuraana** [SelectorsHub/SelectorsHubIssues#51]
Can you please move this close icon to the left along with other buttons so its easily clickable on a bigger screen and more visible

you can make its a button with text over it..and along with X

![image](https://user-images.githubusercontent.com/15048211/195355834-e4af074f-6678-4ad7-a60b-6aa58abc1318.png)

**Comment by selectorshubsanjay** [comment]
We tried it but it looks odd as per UX, we are still thinking if should change the position of close button.
Current position goes good as per UX and it also in sync with devtools close button.

<img width="665" alt="image" src="https://user-images.githubusercontent.com/67390539/199083517-04993da2-b68e-494d-9e51-1bdbcd92b7bf.png">
