### ISSUE TITLE
xpath is not generated. i tried to reinstall and did browser restart as well

### ISSUE THREAD

**Issue by keerthindu** [SelectorsHub/SelectorsHubIssues#59]

**Comment by selectorshubsanjay** [comment]
Hi Keerthi, could you please share more details or connect with us on the live chat in from the website. Thank you.

**Comment by selectorshubsanjay** [comment]
There is some issue while copying the xpath, we are working on it and will fix it asap.

**Comment by selectorshubsanjay** [comment]
The fix is live now. Please update to the latest version - 4.6.5
To update , please follow this tutorial- https://youtu.be/JM4nskyK1go

Kindly let us know if you face any issue.
