### ISSUE TITLE
On entering incorrect xpath- it doesn't give any descriptive message

### ISSUE THREAD

**Issue by Deekshapuri** [SelectorsHub/SelectorsHubIssues#6]
As shown in screenshot, I missed ']' in my xpath but still it is not giving any descriptive error message as shown in https://www.youtube.com/watch?v=yuGRPG75k2I!
<img width="1439" alt="Screenshot 2020-08-17 at 6 53 11 PM" src="https://user-images.githubusercontent.com/24864185/90401119-21468f80-e0bb-11ea-94c7-143c1c6f70a4.png">

P.S: A great tool Sanjay! Loved using it. Thanks for making a good contribution for the Automation community!

**Comment by selectorshubsanjay** [comment]
Thank you Deekshapuri for letting me know this and sharing the details.
Could you please checkout this video,
https://youtu.be/v2DRbQH-C7Q

If issue still persist, please share the website url or connect with me on slack, I will help you. Thank you.
https://join.slack.com/t/selectorshub/shared_invite/zt-fho3ep1h-mkjFOdKqmtYWwNVyV8tLSg

**Comment by Deekshapuri** [comment]
Thank you for the help Sanjay! It worked now.
