### ISSUE TITLE
SelectrosHub is visible in Chrome Browser, but not visible in Chrome Driver.

### ISSUE THREAD

**Issue by zohrabzeynalli** [SelectorsHub/SelectorsHubIssues#60]
Hi, when I open Dev tools in Chrome Browser I can see the SelectorsHub extention. However, I am not able to see it, when opening a same website with Selenium which invokes Chrome Driver

**Comment by selectorshubsanjay** [comment]
Please follow this tutorial- https://www.youtube.com/watch?v=-sRAnndI3Fw
