### ISSUE TITLE
Selector Hub not getting displayed in Edge 

### ISSUE THREAD

**Issue by koolsid786** [SelectorsHub/SelectorsHubIssues#61]
Hi Team, 

I have latest version of Edge "Version 110.0.1587.41 (Official build) (64-bit)" I installed the plugin in restarted the browser but Still I cannot find the Selector hub, I have trouble shoot as my end with the steps provided "https://sanjayselectorshub.medium.com/solution-for-all-the-selectorshub-issues-like-not-able-to-find-selectorshub-in-devtools-xpath-not-1a3441b263db" but still not able to locate.

**Comment by selectorshubsanjay** [comment]
Please follow this tutorial 
https://youtu.be/S8Wq0VjqzkU
