### ISSUE TITLE
Screen shot Not Showing URL and Task bar

### ISSUE THREAD

**Issue by nemishnk** [SelectorsHub/SelectorsHubIssues#64]
When ever a screen shot is taken - Address URL and Time in task bar is not shown. Can i get the whole screen when ever a screen shot is taken.

**Comment by selectorshubsanjay** [comment]
This is not possible as chrome doesn't allow this due to security policy.
In TestCase Studio Pro version, we have separate column of URL, which will solves this problem. This column has url for each step.

**Comment by nemishnk** [comment]
Can we have the datetime embedded in the screen shot?

**Comment by selectorshubsanjay** [comment]
Sure, we will check this. Though when you download the screenshot, it will that time when it was created.
