### ISSUE TITLE
Feature Request - Option to generate Text based Xpath

### ISSUE THREAD

**Issue by gauravkhuraana** [SelectorsHub/SelectorsHubIssues#66]
There should be a checkbox which should generated text based xpath
As of now I see my text based xpath in index based. The problem there is its telling the index as [1] when there is just one element i dont need to use index, so specifically asking for text based 
Also possible index based might not be text based for few elements.

so please do give an option to see only the text based xpath

![image](https://github.com/SelectorsHub/SelectorsHubIssues/assets/15048211/2a96dd8e-57a2-4d7d-a5ea-f857512f8654)

There are chances we have other unique thing for element but we may need only text based

**Comment by selectorshubsanjay** [comment]
This can be done even now. Like you uncheck those attribute with which it is generating and then it will go for other attribute preference. We already have Text checkbox and input box for "not attribute".
Having too many checkbox will confuse users. We will see in future if that will have a major need.
