### ISSUE TITLE
Feature Request - Have numbers along with element identifier to map xpath with element

### ISSUE THREAD

**Issue by gauravkhuraana** [SelectorsHub/SelectorsHubIssues#67]
Sometimes with 1 xpath we get 6 elements. and its difficult to know which portion in DOM matches with what in SHub

So we have to open each element structure in shub to know which one we want

![image](https://github.com/SelectorsHub/SelectorsHubIssues/assets/15048211/4150ed44-3c00-4883-8a98-0c99b12ad681)

you can give something like this along with boxes you already show using the number xpath=1 which is already there when you find element

![image](https://github.com/SelectorsHub/SelectorsHubIssues/assets/15048211/1587580d-fc9f-4ef9-a979-4d9d0221bf64)

**Comment by selectorshubsanjay** [comment]
This feature is already there. If you press next arrow which is shown at the right corner in the input box with match count like <0/13> , it will directly scroll down the DOM to that element and you can see the DOM structure/html of that element.
