### ISSUE TITLE
Feature Request - Axes based xpaths are system generated, need customisation over ther

### ISSUE THREAD

**Issue by gauravkhuraana** [SelectorsHub/SelectorsHubIssues#68]
Give Customisation here like we have on main page. for axes page as well

What if i want to generate based on a particular attribute or on the basis of class or text 

![image](https://github.com/SelectorsHub/SelectorsHubIssues/assets/15048211/ec6f9f6f-c6bc-45ce-b59f-17bbc51202b2)

**Comment by selectorshubsanjay** [comment]
This is already there. You can turn on attribute filter here same as home page before generating the axes xpath. If it doesn't work, kindly let us know,
