### ISSUE TITLE
Feature Request - An option to put escape character in xpath when someone copies based on user preference

### ISSUE THREAD

**Issue by gauravkhuraana** [SelectorsHub/SelectorsHubIssues#69]
When we copy an xpath and paste it in IDE directly between a variable it automatically adds escape characters like \ 

//p[@class="_2gBcQ5"]  <-- if i pastes this inside below, 

webElement element = driver.findElement("") 

there are chances the IDE will automatically adds \ and make it  "//p[@class=\"_2gBcQ5\"] "

in some scenario it does not.. So would be great to give an option from where if we copy then escape character is already added in xpath. We can give this as an optional feature if people want to switch it on

![image](https://github.com/SelectorsHub/SelectorsHubIssues/assets/15048211/e704da77-b20b-41e0-9c59-c560342e15c4)

**Comment by selectorshubsanjay** [comment]
This is expected and done by IDE.
Concept- There can't be two set of same kinds of quote in an string argument.
