### ISSUE TITLE
Unable to match the xpath 

### ISSUE THREAD

**Issue by asmnoman00** [SelectorsHub/SelectorsHubIssues#7]
Hello Sanjay,
First of all thanks a lot to innovate this amazing feature and contribute this in community.It would be great you could assist me why selects hub cant match this element even after showing auto suggestion and select those.After inspect the element in custom control which having different button it highlight me 2 link and selectors hub can not match with its own auto suggest xpath. I might be wrong in my understanding.I appreciate if you could comment on this.
![Capture 1](https://user-images.githubusercontent.com/38882402/91274137-11f0d180-e7a0-11ea-8540-743cfc461c72.JPG)

**Comment by selectorshubsanjay** [comment]
Thank you @asmnoman00 
Sure I will help you. Here you will have to add tagname after // in your xpath as SelectorsHub is suggesting in the message.
So the correct xpath is - //a[contains(text(),'Save & Close']
Actually SelectorsHub suggests the functions for xpath and cssSelectors while typing same like IntelliJ suggests functions while writing code.

If you first type // then it will suggests you //a then you type [ then it will suggest more function along with their occurrences.

To make best use of SelectorsHub, I would recommend you to watch this tutorial-
https://youtu.be/5PYg5GgXSHg

**Comment by asmnoman00** [comment]
Correct xpath is - //a[contains(text(),'Save & Close'] ,it shows error.May be it should be //a[contains(text(),'Save & Close')].After selecting this it works fine.

**Comment by selectorshubsanjay** [comment]
Yes you are right, i missed the ) while typing. Thank you for making it correct.
