### ISSUE TITLE
Request to add feature to indicate users that attribute used by user appears to be dynamic for users to avoid those attributes

### ISSUE THREAD

**Issue by sumit12071988** [SelectorsHub/SelectorsHubIssues#8]
HI Sanjay,
Request you to add this feature to indicate users that attribute used by user appears to be dynamic for users to avoid those attributes

![SelectorsHubIssue](https://user-images.githubusercontent.com/52005517/91380332-4c697580-e857-11ea-8fc4-035b35d1e5b0.png)

**Comment by selectorshubsanjay** [comment]
Thank you Sumit for the feedback. Sure you will get this feature soon in the next release.

**Comment by selectorshubsanjay** [comment]
This feature is added in SelectorsHub 2.0. Now you will see for dynamic values, it will show alert icons. Thank you.
